import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to
 * https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing
}

java {
    // Apply a specific Java toolchain to ease working on different environments.
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
    // Generate javadoc and sources jar for maven central publishing
    withJavadocJar()
    withSourcesJar()
}

group = "fr.insee.ddi"
version = "1.0.0"
val nameForArtifactAndJar by extra("ddi-lifecycle")

repositories {
    // Check maven local dependencies to avoid unnecessary network calls.
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.xmlbeans:xmlbeans:5.2.0")
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("org.apache.logging.log4j:log4j-core:2.21.1")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

sourceSets {
    main {
        java {
            srcDir("src/main/java")
        }
        resources {
            srcDir("src/main/resources")
            srcDir("src/main/ddi-sources")
        }
    }
}

tasks.register("generateSources", type = JavaExec::class) {
    group = "build"
    description = "Generate java sources from DDI xsd"
    classpath = sourceSets["main"].compileClasspath
    mainClass = "org.apache.xmlbeans.impl.tool.SchemaCompiler"
    args(
            "-srconly",
            "-src",
            sourceSets["main"].java.sourceDirectories.asPath,
            "-d",
            sourceSets["main"].resources.sourceDirectories.toList()[0].toPath(),
            sourceSets["main"].resources.sourceDirectories.toList()[1].toPath()
    )
}

tasks.named("generateSources").configure {
    onlyIf {
        fileTree(sourceSets["main"].resources.sourceDirectories.toList()[0]) {
            include("**/*.xsb")
        }.isEmpty
    }
}

tasks.named("compileJava") {
    dependsOn("generateSources")
}

tasks.withType<Copy> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
tasks.withType<Jar> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName = nameForArtifactAndJar
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register("printVersion") {
    doLast {
        println(project.version)
    }
}

tasks {
    javadoc {
        (options as CoreJavadocOptions).addStringOption("Xdoclint:none", "-quiet")
    }
}

/**
 * Publishing is configured for maven central by default.
 * Repository can be configured using a command line argument:
 * ```
 * gradle publish -DrepoUrl="https://example-repo.com/"
 * ```
 */
publishing {

    repositories {
        maven {
            val isSnapshot: Boolean = version.toString().endsWith("SNAPSHOT")
            val snapshotRepo: URI = URI.create("https://oss.sonatype.org/content/repositories/snapshots/")
            val releaseRepo: URI = URI.create("https://oss.sonatype.org/service/local/staging/deploy/maven2/")
            val mavenRepo: URI = if (isSnapshot) snapshotRepo else releaseRepo

            val commandLineRepoUrl = System.getProperty("repoUrl")

            name = "OSSRH"
            url = if (commandLineRepoUrl != null) URI.create(commandLineRepoUrl) else mavenRepo

            val mavenUserProp = System.getenv("OSSRH_USERNAME") ?: findProperty("ossrh.username")
            val mavenPwdProp = System.getenv("OSSRH_PASSWORD") ?: findProperty("ossrh.password")

            if (mavenUserProp != null && mavenPwdProp != null) {
                println("Maven user: $mavenUserProp")
                credentials {
                    username = "$mavenUserProp"
                    password = "$mavenPwdProp"
                }
            }

        }
    }

    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = nameForArtifactAndJar
            from(components["java"])
            pom {
                name = "DDI Lifecycle Java"
                description = "Java classes for DDI Lifecycle"
                url = "https://github.com/InseeFr/DDI-Lifecycle-Java"
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://opensource.org/license/mit/"
                    }
                }
                developers {
                    developer {
                        id = "FBibonne"
                        name = "Fabrice Bibonne"
                    }
                    developer {
                        id = "nsenave"
                        name = "Nicolas Senave"
                        email = "nicolas.senave@insee.fr"
                    }
                }
                scm {
                    url = "https://github.com/InseeFr/DDI-Lifecycle-Java"
                    connection = "scm:git:git://github.com/InseeFr/DDI-Lifecycle-Java.git"
                    developerConnection = "scm:git:ssh://github.com/InseeFr/DDI-Lifecycle-Java.git"
                }
            }
        }
    }

}

// https://docs.gradle.org/current/userguide/signing_plugin.html
signing {
    isRequired = true
    // Environment variables for ascii-armored keys (to be used in CI)
    val privateGPGKey = System.getenv("GPG_SIGNING_KEY")
    val gpgPassword = System.getenv("GPG_PASSWORD")
    if (privateGPGKey != null && gpgPassword != null) {
        useInMemoryPgpKeys(privateGPGKey, gpgPassword)
    }
    // NB: If ascii-armored keys are not given, signing.keyId, signing.secretKeyRingFile, and signing.password
    // properties are used
    sign(publishing.publications["mavenJava"])
}

tasks.withType<Sign> {
    onlyIf {
        System.getProperty("repoUrl") == null && !version.toString().endsWith("SNAPSHOT")
    }
}
